// Forward declarations
// Forward declarations removed to avoid nested class creation inside Engine
// friend class X; is sufficient for global class X if Engine is global

// Friend declarations for FunctionData classes
friend class Command_Default;
friend class Command_KeymapPrevPrefix;
friend class Command_KeymapParent;
friend class Command_KeymapWindow;
// friend class FunctionData_KeymapPrevPrefix; // Replaced
friend class Command_OtherWindowClass;
friend class Command_Prefix;
friend class Command_Keymap;
friend class Command_Sync;
friend class FunctionData_Toggle;
friend class FunctionData_EditNextModifier;
friend class FunctionData_Variable;
friend class FunctionData_Repeat;
friend class FunctionData_Undefined;
friend class FunctionData_Ignore;
friend class FunctionData_PostMessage;
friend class FunctionData_ShellExecute;
friend class FunctionData_SetForegroundWindow;
friend class FunctionData_LoadSetting;
friend class FunctionData_VK;
friend class FunctionData_Wait;
friend class FunctionData_InvestigateCommand;
friend class FunctionData_MayuDialog;
friend class FunctionData_DescribeBindings;
friend class FunctionData_HelpMessage;
friend class FunctionData_HelpVariable;
friend class FunctionData_WindowRaise;
friend class FunctionData_WindowLower;
friend class FunctionData_WindowMinimize;
friend class FunctionData_WindowMaximize;
friend class FunctionData_WindowHMaximize;
friend class FunctionData_WindowVMaximize;
friend class FunctionData_WindowHVMaximize;
friend class FunctionData_WindowMove;
friend class FunctionData_WindowMoveTo;
friend class FunctionData_WindowMoveVisibly;
friend class FunctionData_WindowMonitorTo;
friend class FunctionData_WindowMonitor;
friend class FunctionData_WindowClingToLeft;
friend class FunctionData_WindowClingToRight;
friend class FunctionData_WindowClingToTop;
friend class FunctionData_WindowClingToBottom;
friend class FunctionData_WindowClose;
friend class FunctionData_WindowToggleTopMost;
friend class FunctionData_WindowIdentify;
friend class FunctionData_WindowSetAlpha;
friend class FunctionData_WindowRedraw;
friend class FunctionData_WindowResizeTo;
friend class FunctionData_MouseMove;
friend class FunctionData_MouseWheel;
friend class FunctionData_ClipboardChangeCase;
friend class FunctionData_ClipboardUpcaseWord;
friend class FunctionData_ClipboardDowncaseWord;
friend class FunctionData_ClipboardCopy;
friend class FunctionData_EmacsEditKillLinePred;
friend class FunctionData_EmacsEditKillLineFunc;
friend class FunctionData_LogClear;
friend class FunctionData_Recenter;
friend class FunctionData_DirectSSTP;
friend class FunctionData_PlugIn;
friend class FunctionData_SetImeStatus;
friend class FunctionData_SetImeString;
friend class FunctionData_MouseHook;
friend class FunctionData_CancelPrefix;
