#!/bin/bash
# Simple Mapping Test - Type in a text editor and see what happens

echo "════════════════════════════════════════════════════════════════"
echo "  YAMY Simple Mapping Test"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Expected Dvorak-like W-row mappings (config_clean.mayu):"
echo ""
echo "  Physical QWERTY: Q  W  E  R  T  Y  U  I  O  P"
echo "  Should output:   -  A  O  E  U  I  D  H  T  N"
echo ""
echo "Test: Open a text editor (like gedit or mousepad) and type:"
echo ""
echo "  qwertyuiop"
echo ""
echo "You should see:"
echo ""
echo "  -aoeuidhtn"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Other important mappings to test:"
echo ""
echo "  Press 'A' → Should type TAB"
echo "  Press 'B' → Should type ENTER (new line)"
echo "  Press 'V' → Should type BACKSPACE (delete previous char)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "If these don't work, YAMY may not be processing keys."
echo "Check YAMY status:"
echo ""
echo "  ./build/bin/yamy-ctl status"
echo ""
echo "Check debug log:"
echo ""
echo "  tail -f /tmp/yamy_debug.log | grep LAYER"
echo ""
